### ISSUE TITLE
Computation schema needs some changes

### ISSUE THREAD

**Issue by lzehl** [HumanBrainProject/openMINDS_computation#11]
Based on the PR https://github.com/HumanBrainProject/openMINDS_core/pull/204 some changes are required for the Computation schema (e.g., "startedAtTime", "endedAtTime" are now optional properties of Activity).

**Comment by apdavison** [comment]
@lzehl are all the necessary changes now implemented? If so we can close this.

**Comment by lzehl** [comment]
@apdavison yes, I think we got all of them. you can close this issue.
