### ISSUE TITLE
WorkflowRecipeVersion clarifications for components & WorkflowExecution

### ISSUE THREAD

**Issue by lzehl** [HumanBrainProject/openMINDS_computation#24]
At the moment there are two linkages for the components of a workflow recipe version:
+ direct linkage: property "hasComponent" links to File / FileBundle / SoftwareVersion / WorkflowRecipeVersion with no indication for File / FileBundle / SoftwareVersion to what type of computation they belong to
+ indirect linkage (1): computation schemas (DataAnalysis / Optimization / Simulation / Visualization) link to WorkflowRecipeVersion via "recipe" property and have File / FileBundle / SoftwareVersion linked as input / output (+ ModelVersion for input / output in Optimization and for input in Simulation)
+ indirect linkage (2): computation schemas (DataAnalysis / Optimization / Simulation / Visualization) are linked to WorkflowExecution which in turn links to WorkflowRecipeVersion

Question can we simplify this?

**Comment by apdavison** [comment]
The semantics of these links are very different.

the "hasComponent" property is for "all workflow recipe versions that are components of this workflow recipe version, as well as the software and/or scripts used in this workflow recipe" (prospective provenance)

the "recipe" property links to the WorkflowRecipe actually used for the given computation (retrospective provenance).

The complexity comes from the hierarchical nature of workflows. We have a WorkflowRecipe for the overall WorkflowExecution, which consists of a sub-recipe for each of the individual computations.

**Comment by lzehl** [comment]
@apdavison I assumed as much that the components are different from the execution, but the Execution and the retrospective provenance should be the same no?

**Comment by apdavison** [comment]
yes, they are the same.

**Comment by lzehl** [comment]
Then we should reduce them. Two approaches:

A) 
+ remove "recipe" from computation schemas
Result: WorkflowExecution will point to WorkflowRecipeVersion and the respective computation schemas. This means that computation schemas and WRV are only linked indirectly via WE, but it would have the advantage that WEs can be added continuously without modifying the existing WRV. 

B) 
+ remove "recipe" from computation schemas
+ remove "recipe" from WorkflowExecution schema
+ add property "workflowExecution" to WorkflowRecipeVersion linking to WorkflowExecution (can be an array: 1-N)
Result: WorkflowRecipeVersion would link to all WorkflowExecutions with respective computation schemas. This means that WRV needs to be updated with every new WE.

What I don't like here is that there is no actual generic recipe (version) defined stating which computation is done in which order. Could that be something we can add in addition to the  WorkflowRecipeVersion or the WorkflowRecipe? This would probably require additional schemas.

**Comment by apdavison** [comment]
(A) is possible, but, as you say, the links between the individual computation stages and the associated sub-recipe would then be indirect, which means they would have to be inferred, which would at least require reading the content of the recipe files, and may not be possible to do unambiguously given that workflow stages can happen in parallel.

(B) has the same problem as (A), and adds a new problem that we have to update the WorkflowRecipeVersion every time we run a workflow (which could be hundreds or thousands of times)!


The WRV contains the information about which computation should be done in which order. Are you suggesting having that information directly available in the KG metadata without having to read the WRV file? This is something we've discussed in workflow meetings. A simple approach would be to separate "hasComponent" into two properties, one containing files and software, the other only WRVs, and then the array order for the latter could be interpreted as the order of execution. This wouldn't support parallel or conditional stages though, we would need additional schemas for this.

**Comment by lzehl** [comment]
@apdavison you are right that the indirect linkage between computational schemas and WRV would remain, but that's expected in graph structures no? I don't see another solution since now you even add a validation issue on top of the indirect relation:
+ the WRV that is linked from a computational schema needs to be the same as the one that is linked from one of many WE which link as well to this WRV

I think the usage is still a bit unclear to me. And I may have misunderstood what you mean with prospective and retrospective. 

Let me summarize how assumed your approach should work:

A WorkflowRecipe should in principle define that a certain set of computations have to be executed in a certain way according to the recipe. Examples: 
(A) data are first analyzed and then visualized (DataAnalysis is followed by Visualization)
(B) data are analyzed in parallel in two different ways and the results are visualized simultaneously (two different DataAnalysis are executed in parallel and followed by a joint Visualization)
Currently the overall WorkflowRecipe information is given in free-text form via the description field. For a structured way of defining an overall workflow we would need additional schemas.

While the WorkflowRecipe would just define the overall element types and their order/sequence, the WorkflowRecipeVersion would define the actual execution of the actual computational elements including all parameters that could be changed between executions.

Does this make sense or did you follow a different approach?

**Comment by apdavison** [comment]
> the indirect linkage between computational schemas and WRV would remain

yes, that's fine. The problem is that inferring the direct linkage would require opening and reading a file, and may still not be possible, so I think we need to keep the direct link.

> overall WorkflowRecipe information is given in free-text form via the description field

No. It should be contained in one of the files linked in the "hasComponent" property (a SnakeMake, CWL YAML format or UNICORE XML or JSON file). We can identify which of the files it is based on the "format" property. It occurs to me that this approach implies too much implicit knowledge, so perhaps we should add a new property "definition" which either links directly to the file, or is a text field (since workflow definitions are not usually very large).

> While the WorkflowRecipe would just define the overall element types and their order/sequence, the WorkflowRecipeVersion would define the actual execution

No. WorkflowRecipe bears the same relationship to WRV as Dataset does to DatasetVersion. The WorkflowExecution reflects the actual execution.

**Comment by lzehl** [comment]
@apdavison

for the second point (which is actually influencing point one): Note that currently the "hasComponent" is not attached to the WR but the WRV. Meaning the high-level definition of the Workflow Recipe is restricted to free-text "description". Generally I think a "definition" property would fit better for the high-level workflow recipe definition. Could we link the core/Configuration schema + core/File schema for "definition", no?

for the latter point (which is actually influencing point one):  do you mean that a single WRV could have multiple WEs ? If yes , could you please describe which component of a workflow is defined in a workflow recipe vs a workflow recipe version vs a workflow execution ?

**Comment by apdavison** [comment]
Yes. Just like you can use a recipe for making a cake to make many cakes, on different occasions.

The "workflow recipe version" defines the steps that should be followed when executing the workflow. The "workflow recipe" groups different versions of a recipe, which may evolve over time (like Software and SoftwareVersion, etc.) The "workflow execution" records the metadata from actually running the workflow.

**Comment by apdavison** [comment]
I didn't know (or had forgotten) about core/Configuration. That might be a good choice, I'll take a look after my holidays.

**Comment by lzehl** [comment]
@apdavison okay. enjoy your holiday :)

**Comment by lzehl** [comment]
Thanks for the discussion. Let's get back to the discussion for merging core/configuration and computation/launchConfiguration when we have more use cases
