### ISSUE TITLE
can environment between computation schema and softwareAgent differ?

### ISSUE THREAD

**Issue by lzehl** [HumanBrainProject/openMINDS_computation#25]
If not the softwareAgent schema is not needed and linkages in computation schemas can be reduced to SoftwareVersion

**Comment by apdavison** [comment]
Usually they will differ. Suppose our SoftwareAgent is Gitlab CI, which runs computations in different VMs. The environment for the agent is that of the server running Gitlab, while the environments for the computations are those of the different available VMs.

**Comment by lzehl** [comment]
so just to be sure: the computation itself can run on an environment that differs from the softwareAgent that started it? meaning the software version listed in this software agent should not be listed under input but only under startedBy, correct?

**Comment by apdavison** [comment]
yes to both questions

**Comment by lzehl** [comment]
perfect than we probably just need to refine the instructions over time. I'm closing the issue then.
