### ISSUE TITLE
Activity doesn't exist in core yet

### ISSUE THREAD

**Issue by olinux** [HumanBrainProject/openMINDS_computation#5]
https://github.com/HumanBrainProject/openMINDS_computation/blob/b88204f3dd31f6f9e7a313e0fde12313af245968/schemas/computation.schema.tpl.json#L3

see https://github.com/HumanBrainProject/openMINDS_core/pull/204

**Comment by lzehl** [comment]
@olinux & @apdavison I've just merged the PR https://github.com/HumanBrainProject/openMINDS_core/pull/204 so the Activity schema is now part of core
